# use java support.
language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - oraclejdk8

# use operating systems.
os:
  - linux

notifications:
  email:
    - rohitvvv@gmail.com
    - rajmahendra@gmail.com
    - jyothiprasadb@gmail.com
